parameters:
    context_services:
        SecretSales\ReportTask\Behat\Service\ReportService: report_service
        SecretSales\ReportTask\Behat\Service\SplitTextService: split_text_service
        SecretSales\ReportTask\Behat\Service\MapService: map_service
        SecretSales\ReportTask\Behat\Service\ReduceService: reduce_service
        SecretSales\ReportTask\Behat\Service\StorageService: reduce_service

services:
    report_service:
        class: SecretSales\ReportTask\Bundle\ReportBundle\Service\PopularWord\ReportService

    map_service:
        class: SecretSales\ReportTask\Bundle\ReportBundle\Service\PopularWord\MapService

    reduce_service:
            class: SecretSales\ReportTask\Bundle\ReportBundle\Service\PopularWord\ReduceService

    split_text_service:
            class: SecretSales\ReportTask\Bundle\ReportBundle\Service\PopularWord\SplitTextService

    storage_service:
            class: SecretSales\ReportTask\Bundle\ReportBundle\Service\PopularWord\StorageService

    service_argument_resolver:
        class: SecretSales\ReportTask\Behat\Context\Argument\ServiceArgumentResolver
        arguments: ["@service_container", "%context_services%"]
        tags:
            - { name: context.argument_resolver }
